name: Say hello
on:
  push:
    branches:
      - main
jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo the message
        run: echo 'hola Abner'
      - name: Dime la fecha
        run: date
      - name: lista
        run: ls -l




