name: Deployment Pipeline

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14 
      
      - name: Install dependencies
        run: npm install
      
      - name: Execute Lint
        run: npm run eslint




