name: Deployment Pipeline

on: 
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Install NODE version
        uses: actions/setup-node@v2
        with:
          node-version: 14 
      
      - name: Install dependencies
        uses: npm install
      
      - name: Execute Lint
        uses: npm run eslint

    



